// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TireServiceAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231119162730_newimgs")]
    partial class newimgs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TireServiceAPI.Models.Cart.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("TireServiceAPI.Models.Cart.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("TireId")
                        .HasColumnType("int");

                    b.Property<int?>("WheelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("TireId");

                    b.HasIndex("WheelId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("TireServiceAPI.Models.Favourite.Favourite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Favourites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("TireServiceAPI.Models.Favourite.FavouriteItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FavouriteId")
                        .HasColumnType("int");

                    b.Property<int?>("TireId")
                        .HasColumnType("int");

                    b.Property<int?>("WheelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FavouriteId");

                    b.HasIndex("TireId");

                    b.HasIndex("WheelId");

                    b.ToTable("FavouriteItems");
                });

            modelBuilder.Entity("TireServiceAPI.Models.Product.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "KAMA"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ROYALBLACK"
                        },
                        new
                        {
                            Id = 3,
                            Name = "FORMULA"
                        });
                });

            modelBuilder.Entity("TireServiceAPI.Models.Product.Diameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Diameters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "12"
                        },
                        new
                        {
                            Id = 2,
                            Name = "13"
                        },
                        new
                        {
                            Id = 3,
                            Name = "14"
                        },
                        new
                        {
                            Id = 4,
                            Name = "15"
                        },
                        new
                        {
                            Id = 5,
                            Name = "16"
                        },
                        new
                        {
                            Id = 6,
                            Name = "17"
                        },
                        new
                        {
                            Id = 7,
                            Name = "18"
                        },
                        new
                        {
                            Id = 8,
                            Name = "19"
                        },
                        new
                        {
                            Id = 9,
                            Name = "20"
                        });
                });

            modelBuilder.Entity("TireServiceAPI.Models.Product.Types.Tire.Tire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Diameter")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("TireCategory")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TireProfile")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TireSeason")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Width")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Brand");

                    b.HasIndex("Diameter");

                    b.HasIndex("TireCategory");

                    b.HasIndex("TireProfile");

                    b.HasIndex("TireSeason");

                    b.HasIndex("Width");

                    b.ToTable("Tires");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "KAMA",
                            Diameter = "14",
                            Image = "tires/1.png",
                            Name = "Breeze (НК-132) TL",
                            Price = 2640,
                            TireCategory = "Легковые",
                            TireProfile = "65",
                            TireSeason = "Летние",
                            Width = "175"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "KAMA",
                            Diameter = "13",
                            Image = "tires/2.png",
                            Name = "Breeze (НК-132) TL",
                            Price = 2660,
                            TireCategory = "Легковые",
                            TireProfile = "70",
                            TireSeason = "Летние",
                            Width = "175"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "KAMA",
                            Diameter = "14",
                            Image = "tires/3.png",
                            Name = "Кама-365 (НК-241) TL",
                            Price = 2700,
                            TireCategory = "Легковые",
                            TireProfile = "65",
                            TireSeason = "Летние",
                            Width = "175"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "ROYALBLACK",
                            Diameter = "15",
                            Image = "tires/4.png",
                            Name = "Royalmile TL",
                            Price = 2710,
                            TireCategory = "Легковые",
                            TireProfile = "70",
                            TireSeason = "Летние",
                            Width = "175"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "KAMA",
                            Diameter = "17",
                            Image = "tires/5.png",
                            Name = "Кама-365 (НК-241) TL",
                            Price = 3011,
                            TireCategory = "Легковые",
                            TireProfile = "55",
                            TireSeason = "Летние",
                            Width = "195"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "KAMA",
                            Diameter = "13",
                            Image = "tires/6.png",
                            Name = "Grant (НК-241) TL",
                            Price = 2988,
                            TireCategory = "Легковые",
                            TireProfile = "60",
                            TireSeason = "Зимние  нешипованные",
                            Width = "205"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "FORMULA",
                            Diameter = "15",
                            Image = "tires/specials/1.png",
                            Name = "ОШЗ ИЯ-112А",
                            Price = 10600,
                            TireCategory = "Грузовые",
                            TireProfile = "50",
                            TireSeason = "Зимние  шипованные",
                            Width = "135"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "FORMULA",
                            Diameter = "15",
                            Image = "tires/specials/2.png",
                            Name = "ОШЗ У-2",
                            Price = 12033,
                            TireCategory = "Грузовые",
                            TireProfile = "65",
                            TireSeason = "Летние",
                            Width = "155"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "ROYALBLACK",
                            Diameter = "17",
                            Image = "tires/specials/3.png",
                            Name = "BKT FL-252",
                            Price = 4481,
                            TireCategory = "Спецшины",
                            TireProfile = "70",
                            TireSeason = "Летние",
                            Width = "195"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "FORMULA",
                            Diameter = "14",
                            Image = "tires/specials/4.png",
                            Name = "solid /std/ Starco Tusker TL",
                            Price = 5442,
                            TireCategory = "Спецшины",
                            TireProfile = "55",
                            TireSeason = "Зимние  нешипованные",
                            Width = "195"
                        });
                });

            modelBuilder.Entity("TireServiceAPI.Models.Product.Types.Tire.TireCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("TireCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Легковые"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Легкогрузовые"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Грузовые"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Сельхозшины"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Спецшины"
                        });
                });

            modelBuilder.Entity("TireServiceAPI.Models.Product.Types.Tire.TireProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("TireProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "50"
                        },
                        new
                        {
                            Id = 2,
                            Name = "55"
                        },
                        new
                        {
                            Id = 3,
                            Name = "60"
                        },
                        new
                        {
                            Id = 4,
                            Name = "65"
                        },
                        new
                        {
                            Id = 5,
                            Name = "70"
                        },
                        new
                        {
                            Id = 6,
                            Name = "75"
                        },
                        new
                        {
                            Id = 7,
                            Name = "80"
                        },
                        new
                        {
                            Id = 8,
                            Name = "85"
                        });
                });

            modelBuilder.Entity("TireServiceAPI.Models.Product.Types.Tire.TireSeason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("TireSeasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Зимние  нешипованные"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Зимние  шипованные"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Летние"
                        });
                });

            modelBuilder.Entity("TireServiceAPI.Models.Product.Types.Wheel.Wheel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Diameter")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("WheelCategory")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WheelType")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Width")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Brand");

                    b.HasIndex("Diameter");

                    b.HasIndex("WheelCategory");

                    b.HasIndex("WheelType");

                    b.HasIndex("Width");

                    b.ToTable("Wheels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "FORMULA",
                            Diameter = "13",
                            Image = "1",
                            Name = "T.Corolla (53A38R) box Silver (TREBL)",
                            Price = 2640,
                            WheelCategory = "Легковые",
                            WheelType = "Легкосплавный",
                            Width = "175"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "KAMA",
                            Diameter = "17",
                            Image = "wheels/1.png",
                            Name = "ВАЗ-2112 Silver (ТЗСК, Тольятти)",
                            Price = 2660,
                            WheelCategory = "Легковые",
                            WheelType = "Легкосплавный",
                            Width = "195"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "ROYALBLACK",
                            Diameter = "13",
                            Image = "wheels/2.png",
                            Name = "Skoda, VW (63H37D-PCR14605100R) S (Eurodisk)",
                            Price = 4040,
                            WheelCategory = "Грузовые",
                            WheelType = "Стальной",
                            Width = "205"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "ROYALBLACK",
                            Diameter = "15",
                            Image = "wheels/3.png",
                            Name = "Royalmile TL",
                            Price = 2710,
                            WheelCategory = "Грузовые",
                            WheelType = "Стальной",
                            Width = "175"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "KAMA",
                            Diameter = "14",
                            Image = "wheels/4.png",
                            Name = "(AR006) box Silver (TREBL)",
                            Price = 46040,
                            WheelCategory = "Легковые",
                            WheelType = "Легкосплавный",
                            Width = "175"
                        });
                });

            modelBuilder.Entity("TireServiceAPI.Models.Product.Types.Wheel.WheelCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("WheelCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Легковые"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Грузовые"
                        });
                });

            modelBuilder.Entity("TireServiceAPI.Models.Product.Types.Wheel.WheelType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("WheelTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Легкосплавный"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Стальной"
                        });
                });

            modelBuilder.Entity("TireServiceAPI.Models.Product.Width", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Widths");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "135"
                        },
                        new
                        {
                            Id = 2,
                            Name = "155"
                        },
                        new
                        {
                            Id = 3,
                            Name = "175"
                        },
                        new
                        {
                            Id = 4,
                            Name = "185"
                        },
                        new
                        {
                            Id = 5,
                            Name = "195"
                        },
                        new
                        {
                            Id = 6,
                            Name = "205"
                        });
                });

            modelBuilder.Entity("TireServiceAPI.Models.Cart.CartItem", b =>
                {
                    b.HasOne("TireServiceAPI.Models.Cart.Cart", "Carts")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TireServiceAPI.Models.Product.Types.Tire.Tire", "Tire")
                        .WithMany("cartItems")
                        .HasForeignKey("TireId");

                    b.HasOne("TireServiceAPI.Models.Product.Types.Wheel.Wheel", "Wheel")
                        .WithMany("cartItems")
                        .HasForeignKey("WheelId");

                    b.Navigation("Carts");

                    b.Navigation("Tire");

                    b.Navigation("Wheel");
                });

            modelBuilder.Entity("TireServiceAPI.Models.Favourite.FavouriteItem", b =>
                {
                    b.HasOne("TireServiceAPI.Models.Favourite.Favourite", "Favourites")
                        .WithMany("FavouriteItems")
                        .HasForeignKey("FavouriteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TireServiceAPI.Models.Product.Types.Tire.Tire", "Tire")
                        .WithMany("FavouriteItems")
                        .HasForeignKey("TireId");

                    b.HasOne("TireServiceAPI.Models.Product.Types.Wheel.Wheel", "Wheel")
                        .WithMany("FavouriteItems")
                        .HasForeignKey("WheelId");

                    b.Navigation("Favourites");

                    b.Navigation("Tire");

                    b.Navigation("Wheel");
                });

            modelBuilder.Entity("TireServiceAPI.Models.Product.Types.Tire.Tire", b =>
                {
                    b.HasOne("TireServiceAPI.Models.Product.Brand", "Brands")
                        .WithMany("Tires")
                        .HasForeignKey("Brand")
                        .HasPrincipalKey("Name");

                    b.HasOne("TireServiceAPI.Models.Product.Diameter", "Diameters")
                        .WithMany("Tires")
                        .HasForeignKey("Diameter")
                        .HasPrincipalKey("Name");

                    b.HasOne("TireServiceAPI.Models.Product.Types.Tire.TireCategory", "TireCategories")
                        .WithMany("Tires")
                        .HasForeignKey("TireCategory")
                        .HasPrincipalKey("Name");

                    b.HasOne("TireServiceAPI.Models.Product.Types.Tire.TireProfile", "TireProfiles")
                        .WithMany("Tires")
                        .HasForeignKey("TireProfile")
                        .HasPrincipalKey("Name");

                    b.HasOne("TireServiceAPI.Models.Product.Types.Tire.TireSeason", "TireSeasons")
                        .WithMany("Tires")
                        .HasForeignKey("TireSeason")
                        .HasPrincipalKey("Name");

                    b.HasOne("TireServiceAPI.Models.Product.Width", "Widths")
                        .WithMany("Tires")
                        .HasForeignKey("Width")
                        .HasPrincipalKey("Name");

                    b.Navigation("Brands");

                    b.Navigation("Diameters");

                    b.Navigation("TireCategories");

                    b.Navigation("TireProfiles");

                    b.Navigation("TireSeasons");

                    b.Navigation("Widths");
                });

            modelBuilder.Entity("TireServiceAPI.Models.Product.Types.Wheel.Wheel", b =>
                {
                    b.HasOne("TireServiceAPI.Models.Product.Brand", "Brands")
                        .WithMany("Wheels")
                        .HasForeignKey("Brand")
                        .HasPrincipalKey("Name");

                    b.HasOne("TireServiceAPI.Models.Product.Diameter", "Diameters")
                        .WithMany("Wheels")
                        .HasForeignKey("Diameter")
                        .HasPrincipalKey("Name");

                    b.HasOne("TireServiceAPI.Models.Product.Types.Wheel.WheelCategory", "WheelCategories")
                        .WithMany("Wheels")
                        .HasForeignKey("WheelCategory")
                        .HasPrincipalKey("Name");

                    b.HasOne("TireServiceAPI.Models.Product.Types.Wheel.WheelType", "WheelTypes")
                        .WithMany("Wheels")
                        .HasForeignKey("WheelType")
                        .HasPrincipalKey("Name");

                    b.HasOne("TireServiceAPI.Models.Product.Width", "Widths")
                        .WithMany("Wheels")
                        .HasForeignKey("Width")
                        .HasPrincipalKey("Name");

                    b.Navigation("Brands");

                    b.Navigation("Diameters");

                    b.Navigation("WheelCategories");

                    b.Navigation("WheelTypes");

                    b.Navigation("Widths");
                });

            modelBuilder.Entity("TireServiceAPI.Models.Cart.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("TireServiceAPI.Models.Favourite.Favourite", b =>
                {
                    b.Navigation("FavouriteItems");
                });

            modelBuilder.Entity("TireServiceAPI.Models.Product.Brand", b =>
                {
                    b.Navigation("Tires");

                    b.Navigation("Wheels");
                });

            modelBuilder.Entity("TireServiceAPI.Models.Product.Diameter", b =>
                {
                    b.Navigation("Tires");

                    b.Navigation("Wheels");
                });

            modelBuilder.Entity("TireServiceAPI.Models.Product.Types.Tire.Tire", b =>
                {
                    b.Navigation("FavouriteItems");

                    b.Navigation("cartItems");
                });

            modelBuilder.Entity("TireServiceAPI.Models.Product.Types.Tire.TireCategory", b =>
                {
                    b.Navigation("Tires");
                });

            modelBuilder.Entity("TireServiceAPI.Models.Product.Types.Tire.TireProfile", b =>
                {
                    b.Navigation("Tires");
                });

            modelBuilder.Entity("TireServiceAPI.Models.Product.Types.Tire.TireSeason", b =>
                {
                    b.Navigation("Tires");
                });

            modelBuilder.Entity("TireServiceAPI.Models.Product.Types.Wheel.Wheel", b =>
                {
                    b.Navigation("FavouriteItems");

                    b.Navigation("cartItems");
                });

            modelBuilder.Entity("TireServiceAPI.Models.Product.Types.Wheel.WheelCategory", b =>
                {
                    b.Navigation("Wheels");
                });

            modelBuilder.Entity("TireServiceAPI.Models.Product.Types.Wheel.WheelType", b =>
                {
                    b.Navigation("Wheels");
                });

            modelBuilder.Entity("TireServiceAPI.Models.Product.Width", b =>
                {
                    b.Navigation("Tires");

                    b.Navigation("Wheels");
                });
#pragma warning restore 612, 618
        }
    }
}
